FROM python:3.11-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock* ./
RUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi

COPY src/ ./src/

ENV PYTHONPATH=/app/src

EXPOSE 8000

CMD ["python", "-m", "quantstream.api.main"]
